"""crear tablas iniciales

Revision ID: 9698e4eb06fd
Revises: 
Create Date: 2026-03-08 18:55:46.878082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9698e4eb06fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulo',
    sa.Column('id_modulo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_modulo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('permiso',
    sa.Column('id_permiso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('READ', 'WRITE', name='tipopermiso', native_enum=False), nullable=False),
    sa.Column('modulos', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_permiso')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rol', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('rol')
    )
    op.create_table('usuarios',
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('contraseña', sa.String(length=200), nullable=False),
    sa.Column('correo_electronico', sa.String(length=500), nullable=True),
    sa.Column('nombre_completo', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('usuario')
    )
    op.create_table('rol_permiso',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['permiso.id_permiso'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_rol', 'id_permiso')
    )
    op.create_table('usuario_rol',
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario'], ['usuarios.usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario', 'id_rol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_rol')
    op.drop_table('rol_permiso')
    op.drop_table('usuarios')
    op.drop_table('rol')
    op.drop_table('permiso')
    op.drop_table('modulo')
    # ### end Alembic commands ###
