"""Crear tabla email_tokens

Revision ID: email_tokens_001
Revises: fix_propiedades_001
Create Date: 2026-03-22 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'email_tokens_001'
down_revision = 'fix_propiedades_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_tokens',
    sa.Column('id_token', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=6), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id_token')
    )
    op.create_index(op.f('ix_email_tokens_email'), 'email_tokens', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_tokens_email'), table_name='email_tokens')
    op.drop_table('email_tokens')
    # ### end Alembic commands ###
